In [45]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json
from pprint import pprint
# Import API key
from config import g_key

weather_data = pd.read_csv(r'../output_data/cities.csv')
del weather_data['Unnamed: 0']
weather_data

,city,country,latitude,longitude,temperature,humidity,cloudy,wind speed,date
0,Albany,US,42.60,-73.97,72.55,90,47,2.51,1595464521
1,Greeneville,US,36.16,-82.83,81.64,61,1,4.70,1595464722
2,Rikitea,PF,-23.12,-134.97,67.23,59,100,13.65,1595464723
3,Punta Arenas,CL,-53.15,-70.92,28.20,92,77,5.82,1595464682
4,Puerto Escondido,MX,15.85,-97.07,82.40,74,90,2.82,1595464723
...,...,...,...,...,...,...,...,...,...
548,Rocha,UY,-34.48,-54.33,66.18,94,100,8.43,1595464859
549,Sobolevo,RU,54.43,31.90,49.12,95,2,9.98,1595464859
550,Ukiah,US,39.15,-123.21,85.87,31,1,4.70,1595464853
551,At-Bashi,KG,41.17,75.81,53.31,58,0,0.83,1595464859
552,Artigas,UY,-30.40,-56.47,67.28,80,100,6.02,1595464860

In [46]:
locations = weather_data[["latitude", "longitude"]]
humidity = weather_data['humidity']

In [50]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [48]:
ideal_weather = weather_data.loc[weather_data['humidity'] <80 ]
ideal_weather = ideal_weather.loc[ideal_weather['temperature']< 95]
ideal_weather = ideal_weather.loc[ideal_weather['temperature'] > 80]

In [49]:


# geocoordinates
target_coordinates = weather_data[["latitude", "longitude"]]
target_search = 'hotel'
target_radius = 5000
target_type = "hotel"

# set up a parameters dictionary
params = {
    "location": target_coordinates,
    "keyword": target_search,
    "radius": target_radius,
    "type": target_type,
    "key": g_key
}

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"


# run a request using our params dictionary
response = requests.get(base_url, params=params)

hotel_list = response.json()

print(json.dumps(hotel_list, indent=4, sort_keys=True))
#hotel_df = response
#ideal_weather['hotel'] = hotel_df

{
    "html_attributions": [],
    "results": [],
    "status": "INVALID_REQUEST"
}